### ISSUE TITLE
Version 0.9.4 doesn't give possibility to translate pagechooserblock content

### ISSUE THREAD

**Issue by ciloeweb** [wagtail/wagtail-localize#287]
Hello, I implemented a page which contain a pagechooserblock inside Streamfield. I have two locales English and Spanish, I started using wagtail-localized version 0.9.2 and the library related each page with the corresponding locale page and it give me the possibility to edit as you see below:

English Page:
![image](https://user-images.githubusercontent.com/6557784/102832094-14acad80-43b3-11eb-9f30-6d237f0bbbbf.png)

Spanish Page
![image](https://user-images.githubusercontent.com/6557784/102832129-27bf7d80-43b3-11eb-96fa-fdb5895acf61.png)

But when I updated to 0.9.4 version, the library just adds the page id and use the English version without the possibly to edit, it is using the English version.

![image](https://user-images.githubusercontent.com/6557784/102832144-3148e580-43b3-11eb-9db7-4ae55ea80026.png)

I wonder if this is a redesign of the library or it is a bug? Because now I can’t get the content translated.

**Comment by zerolab** [comment]
This was fixed in #480 and available in version 1.0

**Comment by olifante** [comment]
The bug still seems to be there when you subclass StreamBlock and use the PageChooserBlock in your subclass, instead of using it directly in your StreamField. I'm using `wagtail-localize` 1.1 on Wagtail 2.16.1.

Here’s a screenshot showing the differing behaviour between these two cases. The two tasks at the bottom which are incorrectly displaying a page ID of 3 are using a StreamBlock subclass, unlike the otherwise very similar page choosers above it.

![Screenshot 2022-03-22 at 11 04 44](https://user-images.githubusercontent.com/5111/159468019-54a251da-e222-4ea4-a7f9-5de41e752b54.png)

**Comment by zerolab** [comment]
@olifante I've opened #546 that fixes ^.
Made a build at https://zerolab.org/_dumps/wagtail_localize-1.1.1a1-py3-none-any.whl
You can install it via `pip install https://zerolab.org/_dumps/wagtail_localize-1.1.1a1-py3-none-any.whl\#egg\=wagtail_localize` to test locally

**Comment by olifante** [comment]
That build fixes the problem with my code example (PageChooserBlock in a StreamBlock), but I'm still having problems with other pages. One of them happens when we're using a PageChooserBlock inside a StreamBlock inside a StructBlock. I'm going to try to create a minimal example based on our code that highlights the remaining error.

**Comment by zerolab** [comment]
@olifante that use case is one we've solved with @kaedroho post code review. Working on updating tests

**Comment by olifante** [comment]
Great, let me know when you have another build I can test. For what it's worth, here's my code using a PageChooser inside a a StreamBlock inside a StructBlock, which I'm still getting an error with:

```python
class MyStreamBlock(blocks.StreamBlock):
    my_page = blocks.PageChooserBlock()


class MyStructBlock(blocks.StructBlock):
    my_stream = MyStreamBlock()


class HomePage(Page):
    body = StreamField(
        [
            ("inline_page_chooser", blocks.PageChooserBlock()),
            ("stream_block_page_chooser", MyStreamBlock()),
            ("struct_block_page_chooser", MyStructBlock()),
        ],
        blank=True,
    )
    content_panels = Page.content_panels + [
        StreamFieldPanel("body"),
    ]
```

**Comment by zerolab** [comment]
@olifante can you give https://zerolab.org/_dumps/wagtail_localize-1.1.1a2-py3-none-any.whl a try?

**Comment by zerolab** [comment]
Hey @olifante 

I can't reproduce this - https://youtu.be/9r7yR3NlMf8 - and just in case, made a new build - https://zerolab.org/_dumps/wagtail_localize-1.1.1a3-py3-none-any.whl can you give it a go?

**Comment by olifante** [comment]
It's now working for me:
![Screenshot 2022-03-24 at 21 32 26](https://user-images.githubusercontent.com/5111/160014155-6ad65eb4-4d1e-47b9-88ac-4278547bc03c.png)

**Comment by olifante** [comment]
I tried destroying the virtualenv and recreating it. I've had the experience in the past that packages installed from URLs sometimes don't refresh correctly, so maybe that was the problem.

**Comment by chris48s** [comment]
If you hit that again you can do `pip install --upgrade <url>` instead of `pip install <url>` and that should force reinstall of that package. Slightly less nuclear than rebuilding the entire virtualenv :)

**Comment by zerolab** [comment]
@olifante v1.1.1 released (https://github.com/wagtail/wagtail-localize/releases/tag/v1.1.1)

Kudos for the tips @chris48s
